// Rules v0: the first cut, written before the test set existed.
// Do not edit this file after the first scored run. Copy it to rules-v1.mjs
// and tune that instead, so the diff between versions is part of the evidence.
//
// Each rule tests the canonical (fully decoded, NFKC, lower-cased) value of one
// field. `where` limits a rule to certain fields; omit it to test every field.

export const version = 'v0';

export const rules = [
  // SQL injection
  { id: 'sql-tautology', re: /['"`]\s*(or|and)\s+['"`]?\w+['"`]?\s*=\s*['"`]?\w+/, desc: "quote followed by OR/AND x=y, as in ' or '1'='1" },
  { id: 'sql-numeric-tautology', re: /\b(or|and)\s+(\d+)\s*=\s*\2\b/, desc: 'OR/AND n=n, as in 1 or 1=1' },
  { id: 'sql-union-select', re: /\bunion\b[\s\S]*?\bselect\b/, desc: 'UNION ... SELECT' },
  { id: 'sql-select-from', re: /\bselect\b[\s\S]+?\bfrom\b/, desc: 'SELECT ... FROM' },
  { id: 'sql-stacked', re: /;\s*(drop|delete|insert|update|alter|create|truncate|exec|shutdown)\b/, desc: 'stacked statement after a semicolon' },
  { id: 'sql-comment', re: /(['"`)]\s*(--|#)|--\s*$|\/\*[\s\S]*?\*\/)/, desc: 'SQL comment used to cut off a query' },
  { id: 'sql-time-delay', re: /\b(sleep|benchmark|pg_sleep)\s*\(|\bwaitfor\s+delay\b/, desc: 'time-delay function' },
  { id: 'sql-schema', re: /\binformation_schema\b|\bsysobjects\b|\bxp_cmdshell\b/, desc: 'schema or system object' },
  { id: 'sql-bare-quote', re: /^\d*\s*['"`]\s*$/, where: ['query', 'body'], desc: "value that is only a quote, or digits then a quote (Transluce's apostrophe probe)" },

  // Script injection
  { id: 'xss-tag', re: /<\s*\/?\s*[a-z!?]/, desc: 'HTML tag-like text' },
  { id: 'xss-scheme', re: /\b(javascript|vbscript)\s*:|\bdata\s*:\s*text\/html/, desc: 'script URL scheme' },
  { id: 'xss-event-handler', re: /\bon[a-z]{3,}\s*=/, desc: 'inline event handler such as onerror=' },
  { id: 'xss-call', re: /\b(alert|prompt|confirm|eval)\s*\(/, desc: 'script call such as alert(' },

  // Path traversal and file access
  { id: 'path-traversal', re: /\.\.[\/\\]/, desc: '../ or ..\\' },
  { id: 'path-sensitive-file', re: /\/etc\/(passwd|shadow|hosts)\b|\bwin\.ini\b|\bboot\.ini\b|\.env\b|\.git\//, desc: 'well-known sensitive file' },
  { id: 'null-byte', re: /\u0000/, desc: 'null byte' },

  // Command and template injection
  { id: 'cmd-injection', re: /[;|&`]\s*(cat|ls|id|whoami|uname|curl|wget|nc|bash|sh|powershell|cmd)\b/, desc: 'shell command after ; | & or backtick' },
  { id: 'cmd-substitution', re: /\$\([^)]*\)/, desc: 'shell command substitution $(...)' },
  { id: 'template-injection', re: /\{\{[\s\S]*?\}\}|\$\{[\s\S]*?\}/, desc: 'template expression {{...}} or ${...}' },
];
